xbrlmap = {
    "Period End Date"                     : "PeriodEndDate",
    "Period Length"                       : "PeriodLength",
    "Stmt Source"                         : "StmtSource",
    "Stmt Source Date"                    : "StmtSourceDate",
    "Stmt Update Type"                    : "StmtUpdateType",
# balance    
    "Cash and Short Term Investments" : "CashCashEquivalentsAndShortTermInvestments",
    "Cash & Equivalents" : "CashAndEquivalents",
    "Short Term Investments" : "ShortTermInvestments",
    "Total Receivables, Net" : "AccountsNotesReceivableNet",
    "Accounts Receivable - Trade, Net" : "AccountsReceivableNet",
    "Accounts Receivable - Trade, Gross" : "AccountsReceivableGross",
    "Provision for Doubtful Accounts" : "ProvisionForDoubtfulAccounts",
#    "Receivables - Other": "OtherReceivables",
    "Total Inventory" : "InventoryNet",
    "Prepaid Expenses" : "PrepaidExpenses",
    "Other Current Assets, Total" : "OtherCurrentAssets",
    "Total Current Assets" : "TotalCurrentAssets",
    "Property/Plant/Equipment, Total - Net" : "PropertyPlantAndEquipmentNet",
    "Goodwill, Net" : "IntangibleAssetsGoodwill",
    "Intangibles, Net" : "IntangibleAssetsExcludingGoodwillNet",
    "Long Term Investments" : "LongTermInvestments",
    "Note Receivable - Long Term" : "NoteReceivableLongTerm",
    "Other Long Term Assets, Total" : "OtherAssetsNoncurrent", 
    "Other Assets, Total" : "OtherAssets",
    "Total Assets" : "Assets",
    "Accounts Payable" : "AccountsPayable",
    "Payable/Accrued" : "AccruedPayable",
    "Accrued Expenses" : "AccruedExpenses",
    "Notes Payable/Short Term Debt" : "ShortTermDebtAmount",
    "Current Port. of LT Debt/Capital Leases" : "CurrentPortionLongTermDebt",
    "Other Current Liabilities, Total" : "OtherSundryLiabilitiesCurrent",
    "Total Current Liabilities" : "LiabilitiesCurrent",
    "Total Long Term Debt" : "LongTermDebt",
    "Long Term Debt" : "LongTermDebtSubItem",
    "Deferred Income Tax" : "DeferredIncomeTaxes",
    "Minority Interest" : "MinorityInterestBalanceSheet",
    "Other Liabilities, Total" : "OtherNoncurrentLiabilities",
    "Total Liabilities" : "TotalLiabilities",
    "Redeemable Preferred Stock" : "RedeemablePreferredStock",
    "Preferred Stock - Non Redeemable, Net" : "NonRedeemablePreferredStock",
    "Common Stock" : "StockholdersEquityClassCommonStock",
    "Additional Paid-In Capital" : "AdditionalPaidCapital",
    "Retained Earnings (Accumulated Deficit)" : "RetainedEarnings",
    "Treasury Stock - Common" : "TreasuryStock",
    "Other Equity, Total" : "OtherEquity",
    "Total Equity" : "TotalEquity",
    "Total Liabilities & Shareholders Equity" : "LiabilitiesStockholdersEquity",  
    "Total Common Shares Outstanding" : "CommonStockSharesOutstanding",
    "Total Preferred Shares Outstanding" : "PreferredStockSharesOutstanding",
# income
    "Total Revenue" : "OperatingRevenue",
    "Revenue" : "RevenueSubItem",
    "Other Revenue, Total" : "OtherRevenueTotal",
    "Cost of Revenue, Total" : "CostOfRevenue",
    "Gross Profit" : "GrossProfit",
    "Selling/General/Administrative Expenses" : "SellingGeneralAndAdministrativeExpense",
    "Selling/General/Administrative Expenses, Total" : "SellingGeneralAndAdministrativeExpense",
    "Research & Development" : "ResearchAndDevelopmentExpense",
    "Depreciation/Amortization" : "DepreciationAndAmortization",
    "Interest Expense (Income), Net Operating" : "TotalInterestExpense",
    "Unusual Expense (Income)" : "OtherUnusualExpense",
    "Other Operating Expenses, Total" : "OtherOperatingExpense",
    "Operating Income" : "OperatingProfit",
    "Interest Income (Expense), Net Non-Operating" : "InterestIncomeExpenseNet",
    "Gain (Loss) on Sale of Assets" : "GainLossOnSaleOfOtherAssets",
    "Other, Net" : "OtherIncomeLossNet",
    "Income Before Tax" : "IncomeLossContinuingOperationsBeforeIncomeTaxes",
    "Income Tax - Total" : "ProvisionIncomeTaxes",
    "Income After Tax" : "IncomeAfterTax",
    "Minority Interest" : "MinorityInterest",
    "Equity In Affiliates" : "InvestmentAffiliates",
    "U.S. GAAP Adjustment" : "UsGaapAdjustment",
    "Net Income Before Extra. Items" : "NetIncomeBeforeExtraItems",
    "Total Extraordinary Items" : "ExtraordinaryItemsGross" ,
    "Net Income" : "NetIncome",
    "Total Adjustments to Net Income" : "AdjustmentsToNetIncome",
    "Preferred Dividends" : "PreferredDividends",
    "General Partners' Distributions" : "GeneralPartnersDistributions",
    "Basic Weighted Average Shares" : "WeightedAverageNumberOfSharesOutstanding",
    "Basic EPS Excluding Extraordinary Items" : "EarningsPerShareBasicExclExtraItems",
    "Basic EPS Including Extraordinary Items" : "EarningsPerShareBasicInclExtraItems",
    "Diluted Weighted Average Shares" : "WeightedAverageNumberDilutedSharesOutstanding",
    "Diluted EPS Excluding Extrordinary Items" : "DilutedEarningsPerShareNetIncomeExclExtraItems",
    "Diluted EPS Including Extraordinary Items" : "DilutedEarningsPerShareNetIncomeInclExtraItems",
    "Dividends per Share - Common Stock Primary Issue" : "CashDividendsPaidPerShare",
    "Gross Dividends - Common Stock" : "PaymentsOfDividends",
#    "Interest Expense, Supplemental" : "SupplementalInterestExpense"
    "Depreciation, Supplemental" : "SupplementalDepreciationAmortization",
    "Normalized EBITDA" : "NormalizedEBITDA",
    "Normalized EBIT" : "NormalizedEBIT",
    "Normalized Income Before Tax" : "NormalizedIncomeBeforeTax",
    "Normalized Income After Taxes" : "NormalizedIncomeAfterTax",
    "Normalized Income Available to Common" : "NormalizedIncomeAvailableToCommonShareholders",
    "Basic Normalized EPS" : "BasicNormalizedEarningsPerShare",
    "Diluted Normalized EPS" : "DilutedNormalizedEarningsPerShare",
    "Amortization of Intangibles" : "AmortizationOfIntangibles",
# cashflow
    "Net Income/Starting Line" : "NetIncomeStartingLine",
    "Depreciation/Depletion" : "Depreciation",
    "Amortization" : "Amortization",
    "Deferred Taxes" : "DeferredIncomeTaxes",
    "Non-Cash Items" : "NonCashItems",
    "Unusual Items" : "NonCashItems-UnusualItems",
    "Other Non-Cash Items" : "NonCashItems-OtherNonCashItems",
    "Changes in Working Capital" : "ChangesinWorkingCapital",
    "Accounts Receivable" : "ChangesinWorkingCapital-Accounts Receivable",
    "Other Assets" : "ChangesinWorkingCapital-OtherAssets",
    "Other Liabilities" : "ChangesinWorkingCapital-OtherLiabilities",    
    "Cash from Operating Activities" : "NetCashFlowsProvidedUsedOperatingActivities",
    "Capital Expenditures" : "CapitalExpenditures",
    "Purchase of Fixed Assets" : "CapitalExpenditures-PurchaseFixedAssets",
    "Other Investing Cash Flow Items, Total" : "OtherInvestmentCashFlowItems",
    "Acquisition of Business" : "AcquisitionOfBusiness",
    "Sale/Maturity of Investment" : "SaleMaturityOfInvestment",
    "Purchase of Investments" : "PurchaseOfInvestments",
    "Other Investing Cash Flow" : "OtherInvestingCashFlow",
    "Cash from Investing Activities" : "TotalCashInvesting",
    "Financing Cash Flow Items" : "FinancingCashFlowItems",
    "Other Financing Cash Flow" : "OtherFinancingCashFlow",
    "Total Cash Dividends Paid" : "PaymentCommonDividends",
    "Issuance (Retirement) of Stock, Net" : "IssueRetirementOfCommonStockNet",
    "Issuance (Retirement) of Debt, Net" : "NetIssueRetirementOfDebt",
    "Cash from Financing Activities" : "NetCashFlowsProvidedUsedFinancingActivities",
    "Foreign Exchange Effects" : "ForeignExchangeEffects",
    "Net Change in Cash" : "NetIncreaseDecreaseCashCashEquivalents",
    "Net Cash - Beginning Balance" : "NetCashBeginningBalance",
    "Net Cash - Ending Balance" : "NetCashEndingBalance" 
}


# normalized bs list -- each stmt must contain these rows 
bslist = [
"PeriodEndDate",
"StmtSource",
# balance    
"CashCashEquivalentsAndShortTermInvestments",
"CashAndEquivalents",
"ShortTermInvestments",
"AccountsNotesReceivableNet",
"AccountsReceivableNet",
"AccountsReceivableGross",
"ProvisionForDoubtfulAccounts",
"InventoryNet",
"PrepaidExpenses",
"OtherCurrentAssets",
"TotalCurrentAssets",
"PropertyPlantAndEquipmentNet",
"IntangibleAssetsGoodwill",
"IntangibleAssetsExcludingGoodwillNet",
"LongTermInvestments",
"NoteReceivableLongTerm",
"OtherAssetsNoncurrent", 
"OtherAssets",
"Assets",
"AccountsPayable",
"AccruedPayable",
"AccruedExpenses",
"ShortTermDebtAmount",
"CurrentPortionLongTermDebt",
"OtherSundryLiabilitiesCurrent",
"LiabilitiesCurrent",
"LongTermDebt",
"DeferredIncomeTaxes",
"MinorityInterestBalanceSheet",
"OtherNoncurrentLiabilities",
"TotalLiabilities",
"RedeemablePreferredStock",
"NonRedeemablePreferredStock",
"StockholdersEquityClassCommonStock",
"AdditionalPaidCapital",
"RetainedEarnings",
"TreasuryStock",
"OtherEquity",
"TotalEquity",
"LiabilitiesStockholdersEquity",  
"CommonStockSharesOutstanding",
"PreferredStockSharesOutstanding"
]

#normalized income stmt list
islist = [
"PeriodEndDate",
"StmtSource",
"OperatingRevenue",
"RevenueSubItem",
"OtherRevenueTotal",
"CostOfRevenue",
"GrossProfit",
"SellingGeneralAndAdministrativeExpense",
"SellingGeneralAndAdministrativeExpense",
"ResearchAndDevelopmentExpense",
"DepreciationAndAmortization",
"TotalInterestExpense",
"OtherUnusualExpense",
"OtherOperatingExpense",
"OperatingProfit",
"InterestIncomeExpenseNet",
"GainLossOnSaleOfOtherAssets",
"OtherIncomeLossNet",
"IncomeLossContinuingOperationsBeforeIncomeTaxes",
"ProvisionIncomeTaxes",
"IncomeAfterTax",
"MinorityInterest",
"InvestmentAffiliates",
"UsGaapAdjustment",
"NetIncomeBeforeExtraItems",
"ExtraordinaryItemsGross" ,
"NetIncome",
"AdjustmentsToNetIncome",
"PreferredDividends",
"GeneralPartnersDistributions",
"WeightedAverageNumberOfSharesOutstanding",
"WeightedAverageNumberDilutedSharesOutstanding",
"PaymentsOfDividends"
]

#normalized income stmt list
cflist = [
"PeriodEndDate",
"StmtSource",
"NetIncomeStartingLine",
"Depreciation",
"Amortization",
"DeferredIncomeTaxes",
"NonCashItems",
"ChangesinWorkingCapital",
"NetCashFlowsProvidedUsedOperatingActivities",
"CapitalExpenditures",
"OtherInvestmentCashFlowItems",
"AcquisitionOfBusiness",
"SaleMaturityOfInvestment",
"PurchaseOfInvestments",
"OtherInvestingCashFlow",
"TotalCashInvesting",
"FinancingCashFlowItems",
"OtherFinancingCashFlow",
"PaymentCommonDividends",
"IssueRetirementOfCommonStockNet",
"NetIssueRetirementOfDebt",
"NetCashFlowsProvidedUsedFinancingActivities",
"ForeignExchangeEffects",
"NetIncreaseDecreaseCashCashEquivalents",
"NetCashBeginningBalance",
"NetCashEndingBalance" 

]

def getXbrlTag(s):
    """ Get the xbrl tag for string s"""
    try:
        return xbrlmap[s]
    except:
        #print "Xbrl Exception %s"%s
        return s

def getNormalizedList(type):
    if type == "Balance":
        return bslist
    if type == "Income":
        return islist
    if type == "CashFlow":
        return cflist

def demo():
    pass

if __name__ == "__main__":
    demo()
